# Generated by Django 3.2.6 on 2022-11-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertise',
            name='photo',
        ),
    ]
